# Docker Compose for development with live reload
services:
  cubicler-dev:
    build: 
      context: .
      target: development
    ports:
      - "${CUBICLER_PORT:-1503}:${CUBICLER_PORT:-1503}"
    environment:
      - NODE_ENV=development
      - CUBICLER_PORT=1503
      - CUBICLER_SPEC_SOURCE=spec.example.yaml
      - CUBICLER_PROMPT_SOURCE=prompt.example.md
    volumes:
      # Mount source code for live development
      - ./src:/app/src:ro
      - ./spec.example.yaml:/app/spec.example.yaml:ro
      - ./prompt.example.md:/app/prompt.example.md:ro
      # Mount node_modules as a volume to avoid overwriting
      - /app/node_modules
    command: ["node", "--watch", "src/index.js"]
    restart: unless-stopped
