# Docker Compose for development with live reload
services:
  cubicler-dev:
    build: 
      context: .
      target: development
    ports:
      - "${CUBICLER_PORT:-1503}:${CUBICLER_PORT:-1503}"
    environment:
      - NODE_ENV=development
      - CUBICLER_PORT=${CUBICLER_PORT:-1503}
      - CUBICLER_STRICT_PARAMS=${CUBICLER_STRICT_PARAMS:-false}
      
      # Timeout configurations
      - DEFAULT_CALL_TIMEOUT=${DEFAULT_CALL_TIMEOUT:-30000}
      - PROVIDER_CALL_TIMEOUT=${PROVIDER_CALL_TIMEOUT}
      - AGENT_CALL_TIMEOUT=${AGENT_CALL_TIMEOUT}
      
      # New orchestration architecture - using example files
      - CUBICLER_PROMPTS_SOURCE=/app/prompts.example.md
      - CUBICLER_AGENTS_LIST=/app/agents.example.yaml
      - CUBICLER_PROVIDERS_LIST=/app/providers.example.yaml
    volumes:
      # Mount source code for live development
      - ./src:/app/src:ro
      # Mount example configuration files
      - ./prompts.example.md:/app/prompts.example.md:ro
      - ./agents.example.yaml:/app/agents.example.yaml:ro
      - ./providers.example.yaml:/app/providers.example.yaml:ro
      # Mount node_modules as a volume to avoid overwriting
      - /app/node_modules
    command: ["sh", "-c", "npm run build && npm start"]
    restart: unless-stopped
