# Cubicler Server Configuration Example
# This file shows how to configure JWT authentication for Cubicler endpoints
# 
# To use this configuration:
# 1. Copy this file to your desired location (e.g., ./server-config.yaml)
# 2. Set the CUBICLER_SERVER_CONFIG environment variable to point to your config file
# 3. Configure the required environment variables for JWT secrets

server:
  # Server binding configuration
  port: 1503
  host: "0.0.0.0"
  
  # Global JWT authentication (applied to all endpoints unless overridden)
  auth:
    jwt:
      secret: "${JWT_SECRET}"                    # JWT secret for token verification
      issuer: "cubicler-instance"               # Expected issuer claim (optional)
      audience: "cubicler-api"                  # Expected audience claim (optional)
      algorithms: ["HS256", "RS256"]            # Allowed JWT algorithms (optional)
      required: true                            # Whether JWT is required (default: true)
  
  # Per-endpoint authentication configuration (overrides global settings)
  endpoints:
    # JWT authentication for /dispatch endpoint
    dispatch:
      path: "/dispatch"                         # Endpoint path (informational)
      auth:
        jwt:
          secret: "${DISPATCH_JWT_SECRET}"      # Dispatch-specific JWT secret
          audience: "dispatch-api"              # Dispatch-specific audience
          algorithms: ["HS256"]                 # Dispatch-specific algorithms
    
    # JWT authentication for /mcp endpoint  
    mcp:
      path: "/mcp"                              # Endpoint path (informational)
      auth:
        jwt:
          secret: "${MCP_JWT_SECRET}"           # MCP-specific JWT secret
          audience: "mcp-api"                   # MCP-specific audience
          issuer: "mcp-auth-server"             # MCP-specific issuer
          algorithms: ["RS256"]                 # MCP-specific algorithms (public key crypto)

# Environment Variables Required:
# 
# Global JWT:
# JWT_SECRET=your-global-jwt-secret-here
# 
# Endpoint-specific JWT:
# DISPATCH_JWT_SECRET=your-dispatch-specific-secret
# MCP_JWT_SECRET=your-mcp-specific-secret
#
# To disable JWT authentication completely, remove the auth sections above.
# To disable JWT for specific endpoints, remove the endpoint from the endpoints section.